#!/usr/bin/perl

use File::Find;
my $name = ".git-preserve-permissions";
my $fh;

sub wanted {
    if (!($File::Find::name eq $File::Find::dir)) {
        my ($mode, $uid, $gid) = (lstat($_))[2,4,5];
        print $fh "$mode:$uid:$gid:$_\n";
    }
}

my $fileexists = 'false';
if (-e $name) {
    $fileexists = 'true';
}

open($fh, "> $name") or die "Could not open file: $name\n";

find({wanted => \&wanted, no_chdir => 1}, '.');

close($fh);

if ($fileexists eq 'false') {
    print "File $name created. You may want to add it to your repository.\n"
}
