#!/usr/bin/perl

use File::Find;
my $name = ".git-preserve-permissions";
my $fh;

sub save_permissions {
    my $file = $_;
    if (-e $file || -l $file) {
        my ($mode, $uid, $gid) = (lstat($_))[2,4,5];
        print $fh "$mode:$uid:$gid:$_\n";
    } else {
        print "WARNING: A file reported by `git ls-files` doesn't exist: $_\n";
    }
}

my $fileexists = 'false';
if (-e $name) {
    $fileexists = 'true';
}

open($fh, "> $name") or die "Could not open file: $name\n";

$output = `git ls-files`;
foreach ( split("\n", $output) ) {
    save_permissions $_;
}

close($fh);

if ($fileexists eq 'false') {
    print "File $name created. You may want to add it to your repository.\n"
}
