#!/usr/bin/perl

use File::Find;
my $name = ".git-preserve-permissions";
my $fh;
my @changed_files;

if (! -e $name) {
    print "git-preserve-permissions-check: $name does not exists.\n";
    print "use git preserve-permissions-save to initialize it.\n";
    exit 0
}

open($fh, "< $name") or die "Could not open file: $name\n";

while ( ! eof($fh) ) {
    defined( $_ = <$fh> ) or die "readline failed: $!";
    chomp;
    my ($mode, $uid, $gid, $file) = split(/:/);
    if (-e $file) {
        my ($actual_mode, $actual_uid, $actual_gid) = (lstat($file))[2,4,5];
        if (($mode != $actual_mode) or
            ($uid  != $actual_uid)  or
            ($gid  != $actual_gid)) {
                push(@changed_files, $file);
        }
    }
}

close($fh);

if (scalar(@changed_files) != 0) {
    print "Some file(s) has change\n";
    foreach (@changed_files) {
        print "$_\n";
    }
    exit 1;
}
