#!/usr/bin/perl

use File::Find;
my $name = ".permissions.save";
my $fh;

sub wanted {
    if (!($File::Find::name eq $File::Find::dir)) {
        my ($mode, $uid, $gid) = (lstat($_))[2,4,5];
        print $fh "$mode:$uid:$gid:$_\n";
    }
}

open($fh, "> $name") or die "Could not open file: $name\n";

find({wanted => \&wanted, no_chdir => 1}, '.');

close($fh);
