#!/bin/bash
git preserve-permissions --check
return_code="$?"
if [ "${return_code}" != "0" ]; then
    autosave=$(git config --bool --get preserve-permissions.autosave)
    autosavePatch=$(git config --bool --get preserve-permissions.autosavePatch)
    gpp_file=$(git config --bool --get preserve-permissions.file)
    [ -z "${autosave}" ] && autosave="true"
    [ -z "${autosavePatch}" ] && autosavePatch="false"
    if [ "${autosave}" = "false" ]; then
        echo "Execute 'git preserve-permissions --save' to save new permissions"
        echo "Then 'git add ${gpp_file}' and redo your commit"
    elif [ "${autosavePatch}" = "true" ]; then
        git preserve-permissions --save
        exec < /dev/tty
        git add -p "${gpp_file}"
        return_code=$?
    else
        git preserve-permissions --save
        git add "${gpp_file}"
        return_code=$?
    fi
    exit ${return_code}
fi
